language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  # - VERSION="8.0" LINT_CHECK="1" TESTS="0" #TODO: Fix from original repo
  - VERSION="8.0" ODOO_REPO="Vauxoo/odoo" LINT_CHECK="0" TESTS="1"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

services:
  - postgresql

script:
    - travis_run_tests

after_success:
  - travis_after_tests_success
